###
GET   http://localhost:8088/collection/getData


###
POST http://localhost:8088/collection/insertBookMark
Content-Type: "application/json"

{
  "title":"my first bookmark title ",
  "pageUrl":"http://www.baidu.com",
}